# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20180319_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Weathers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='城市名<10字', max_length=10)),
                ('date', models.DateField()),
                ('condition', models.CharField(default='天气状况<10字', max_length=10)),
                ('tempreture_low', models.IntegerField(default=0)),
                ('tempreture_high', models.IntegerField(default=100)),
            ],
        ),
    ]
