# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_news_weathers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(default='???', max_length=10),
        ),
    ]
